import { GetBrowser } from './GetBrowser';
import { isChrome } from './isChrome';
import { isEdge } from './isEdge';
import { isFirefox } from './isFirefox';
import { isMobileSafari } from './isMobileSafari';
import { isMSIE } from './isMSIE';
import { isOpera } from './isOpera';
import { isSafari } from './isSafari';
import { isSilk } from './isSilk';
import { isTrident } from './isTrident';
declare const _default: {
    GetBrowser: typeof GetBrowser;
    isChrome: typeof isChrome;
    isEdge: typeof isEdge;
    isFirefox: typeof isFirefox;
    isMobileSafari: typeof isMobileSafari;
    isMSIE: typeof isMSIE;
    isOpera: typeof isOpera;
    isSafari: typeof isSafari;
    isSilk: typeof isSilk;
    isTrident: typeof isTrident;
};
export default _default;
export * from './GetBrowser';
export * from './isChrome';
export * from './isEdge';
export * from './isFirefox';
export * from './isMobileSafari';
export * from './isMSIE';
export * from './isOpera';
export * from './isSafari';
export * from './isSilk';
export * from './isTrident';
//# sourceMappingURL=index.d.ts.map