import { GetOS } from './GetOS';
import { isAndroid } from './isAndroid';
import { isChromeOS } from './isChromeOS';
import { isCordova } from './isCordova';
import { isCrosswalk } from './isCrosswalk';
import { isEjecta } from './isEjecta';
import { isElectron } from './isElectron';
import { isiOS } from './isiOS';
import { isKindle } from './isKindle';
import { isLinux } from './isLinux';
import { isMacOS } from './isMacOS';
import { isNode } from './isNode';
import { isNodeWebkit } from './isNodeWebkit';
import { isWebApp } from './isWebApp';
import { isWindows } from './isWindows';
import { isWindowsPhone } from './isWindowsPhone';
declare const _default: {
    GetOS: typeof GetOS;
    isAndroid: typeof isAndroid;
    isChromeOS: typeof isChromeOS;
    isCordova: typeof isCordova;
    isCrosswalk: typeof isCrosswalk;
    isEjecta: typeof isEjecta;
    isElectron: typeof isElectron;
    isiOS: typeof isiOS;
    isKindle: typeof isKindle;
    isLinux: typeof isLinux;
    isMacOS: typeof isMacOS;
    isNode: typeof isNode;
    isNodeWebkit: typeof isNodeWebkit;
    isWebApp: typeof isWebApp;
    isWindows: typeof isWindows;
    isWindowsPhone: typeof isWindowsPhone;
};
export default _default;
export * from './GetOS';
export * from './isAndroid';
export * from './isChromeOS';
export * from './isCordova';
export * from './isCrosswalk';
export * from './isEjecta';
export * from './isElectron';
export * from './isiOS';
export * from './isKindle';
export * from './isLinux';
export * from './isMacOS';
export * from './isNode';
export * from './isNodeWebkit';
export * from './isWebApp';
export * from './isWindows';
export * from './isWindowsPhone';
//# sourceMappingURL=index.d.ts.map