import { Android } from './Android';
import { ChromeOS } from './ChromeOS';
import { Cordova } from './Cordova';
import { Crosswalk } from './Crosswalk';
import { Ejecta } from './Ejecta';
import { Electron } from './Electron';
import { GetOS } from './GetOS';
import { iOS } from './iOS';
import { Kindle } from './Kindle';
import { Linux } from './Linux';
import { MacOS } from './MacOS';
import { Node } from './Node';
import { NodeWebkit } from './NodeWebkit';
import { WebApp } from './WebApp';
import { Windows } from './Windows';
import { WindowsPhone } from './WindowsPhone';
export declare const OS: {
    Android: typeof Android;
    ChromeOS: typeof ChromeOS;
    Cordova: typeof Cordova;
    Crosswalk: typeof Crosswalk;
    Ejecta: typeof Ejecta;
    Electron: typeof Electron;
    GetOS: typeof GetOS;
    iOS: typeof iOS;
    Kindle: typeof Kindle;
    Linux: typeof Linux;
    MacOS: typeof MacOS;
    Node: typeof Node;
    NodeWebkit: typeof NodeWebkit;
    WebApp: typeof WebApp;
    Windows: typeof Windows;
    WindowsPhone: typeof WindowsPhone;
};
//# sourceMappingURL=index.d.ts.map