import { GetOS } from './GetOS';
import { isAndroid } from './isAndroid';
import { isChromeOS } from './isChromeOS';
import { isCordova } from './isCordova';
import { isCrosswalk } from './isCrosswalk';
import { isEjecta } from './isEjecta';
import { isElectron } from './isElectron';
import { isiOS } from './isiOS';
import { isKindle } from './isKindle';
import { isLinux } from './isLinux';
import { isMacOS } from './isMacOS';
import { isNode } from './isNode';
import { isNodeWebkit } from './isNodeWebkit';
import { isWebApp } from './isWebApp';
import { isWindows } from './isWindows';
import { isWindowsPhone } from './isWindowsPhone';
export declare const OS: {
    Android: typeof isAndroid;
    ChromeOS: typeof isChromeOS;
    Cordova: typeof isCordova;
    Crosswalk: typeof isCrosswalk;
    Ejecta: typeof isEjecta;
    Electron: typeof isElectron;
    GetOS: typeof GetOS;
    iOS: typeof isiOS;
    Kindle: typeof isKindle;
    Linux: typeof isLinux;
    MacOS: typeof isMacOS;
    Node: typeof isNode;
    NodeWebkit: typeof isNodeWebkit;
    WebApp: typeof isWebApp;
    Windows: typeof isWindows;
    WindowsPhone: typeof isWindowsPhone;
};
//# sourceMappingURL=index.d.ts.map